version: '3'  # if no version is specificed then v1 is assumed. Recommend v2 minimum

services:  # containers. same as docker run
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: frontend-test
    restart: on-failure
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules # internal volumes
      - .:/app # bind volumes
